#!/bin/bash
#============================================================================
# Title       : multicollect
# Description : runs collectawr on multiple hosts and gets the ZIP files
# Author      : Bart Sjerps <bart@outrun.nl>
# License     : GPLv3+
# ---------------------------------------------------------------------------
die() { echo "$(basename $0) error: $@" >&2 ; exit 20; }

# By default, the zip files are placed in $HOME/collectawr-<hostname>.zip
# Change this to another location here:
outdir=$HOME

# The list of machines is defined here
machines=$HOME/machines

# Test if pdsh is installed
test -x /usr/bin/pdsh || die "pdsh not installed, try: yum install pdsh"

# Test if machines file exists
test -f $machines || die "$machines does not exist, creat it first"

# Run the collection on all machines, forward cmdline options to remote cmd
pdsh -w ^$machines dbcollect "$@"

# SCP the zip files to the local system
for m in $(cat $machines); do
  scp ${m}:/tmp/dbcollect.zip $outdir/dbcollect-${m}.zip
done
