#!/bin/bash
#============================================================================
# Title       : mkapp
# Description : Creates ZIPAPP package
# Author      : Bart Sjerps <bart@dirty-cache.com>
# License     : GPLv3+
# ---------------------------------------------------------------------------

set -e
export gitdir=$(git rev-parse --show-toplevel) || exit 10
export packager=$(git config --global user.name)
export email=$(git config --global user.email | sed 's/@/ AT /')
export progname=dbcollect

die() { echo "$(basename $0) error: $@" >&2 ; exit 20 ; }

cat << EOF > "$gitdir"/src/dbcollect/lib/buildinfo.py
buildinfo = {
    'builddate': '$(date +"%Y-%m-%d %H:%M")',
    'branch': '$(git branch --show-current)',
    'tag': '$(git describe --abbrev=0)',
    'describe': '$(git describe --dirty)',
    'packager': '$packager <$email>',
    'buildhash': '$(git rev-parse --verify HEAD)',
    'shorthash': '$(git rev-parse --short HEAD)'
}
EOF

makeapp() {
  echo "Creating $1"
  python3 -m zipapp \
	--output "$1" \
	--main dbcollect:main \
	--python "/usr/bin/env python" \
	 $gitdir/src/$progname
}

#============================================================================
# Main section - parsing options etc
# ---------------------------------------------------------------------------

export outdir=/tmp

while getopts ":d:" OPT; do
case "$OPT" in
  d) outdir=$OPTARG;;
  ?) die "Unknown option -$OPTARG" ;;
esac
done ; shift $(expr $OPTIND - 1)

makeapp  $outdir/$progname
ls -ld   $outdir/$progname
unzip -l $outdir/$progname
ls -l    $outdir/$progname
