#!/bin/bash
#============================================================================
# Title       : mkrelease
# Description : Build a new dbcollect version with tag and push it on git
# Author      : Bart Sjerps <bart@dirty-cache.com>
# License     : GPLv3+
# Copyright   : Copyright (c) 2024 - Bart Sjerps <bart@dirty-cache.com>
# ---------------------------------------------------------------------------
# Internal use only

dir=$(git rev-parse --show-toplevel)
cd $dir/src/dbcollect
version=$(python -c 'from lib.config import versioninfo; print(versioninfo["version"])')

git tag -a -mversion v${version}
git push --tags
