#!/bin/bash

dir=$(git rev-parse --show-toplevel)
cd $dir/src/dbcollect
version=$(python -c 'from lib.config import versioninfo; print(versioninfo["version"])')

git tag -a -mversion v${version}
git push --tags
